### ISSUE TITLE
object that has object as a value

### ISSUE THREAD

**Issue by codelover2k** [redis/redis-om-node#163]
Is it possible to store an object that looks like this?

```js
{
  id: "42",
  username: "peter.private",
  contact: {
    id: "121",
    firstName: "Peter",
    lastName: "Parker",
  }
}
```

if it is possible, how do you define the schema for that?
I know that this is not possible: 
```js
  const userSchema = new Schema(User, {
    id: { type: 'string' },
    username: { type: 'string' },
    contact: { 
      id: { type: 'string' },
      firstName: { type: 'string' },
      lastName: { type: 'string' },
    },
  }, {
    dataStructure: 'JSON',
  });
```

**Comment by guyroyse** [comment]
Check out the beta version of Redis OM 0.4.0. It adds support for nested objects and simplifies what is required in a Schema. You can install it with `npm install redis-om@beta` command.

In the beta you only need to add types to your Schema if you want to search on them or perform conversions on them. If it's nested, you need to specify a `path` property. Otherwise, you can just shove whatever JSON you want in an it works. Entity is gone. So, a schema that would allow you to search on the above might be:

```javascript
const schema = new Schema('my:schema:name', {
  id: { type: 'string' },
  username: { type: 'string' }
  firstName: { type: 'string', path: '$.contact.firstName' },
  lastName: { type: 'string', path: '$.contact.lastName' }
})
```
When you search with this, use the name. For example:
```javascript
const thing = repository.search().where('firstName').equals('Peter').return.first()
```
But the entities you get back will contain your original structure:
```javascript
console.log(thing)
/* RETURNS
{
  id: "42",
  username: "peter.private",
  contact: {
    id: "121",
    firstName: "Peter",
    lastName: "Parker",
  }
}
*/
```
It's worth noting that things like dates are stored as numbers. If you add them to your Schema, Redis OM will convert them for you. If you don't, it will save them as a number and then return that number when you query it.

**Comment by yanmifeakeju** [comment]
How do you get typescript types from the nesting working typescript?
