### ISSUE TITLE
How can i make this queries using this api ?

### ISSUE THREAD

**Issue by fabiel-leon** [redis/redis-om-node#173]
how can i remove index also removing documents using this api ? 
```
FT.DROPINDEX myIdx DD
```

and query the index without specifying  a field ?
```
FT.SEARCH myIdx "hello world" LIMIT 0 10
```

**Comment by guyroyse** [comment]
The DD option is not available from Redis OM. So, the short answer is that you can’t.

Regarding your second question. You can bypass the fluent search interface in Redis OM by calling `.searchRaw` instead of `.search`. Just pass in your raw query and then use the various `.return.*` mechanism as normal.
