### ISSUE TITLE
No way to return specific fields in redis json when using the search functionality.

### ISSUE THREAD

**Issue by errorcodezero** [redis/redis-om-node#193]
```
 const results = await userRepository
    .search()
    .where("name")
    .matches(data.query)
    .return.all()
```
When I use this, it returns everything about the user as defined in the schema. However, it also returns the password. I don't think that redis-om has a builtin way to only get specific fields using the search or fetch functionality. What I mean by that is that I want all the users to be returned, but only specific fields(eg: not the password field).

**Comment by guyroyse** [comment]
Redis OM for Node.js doesn't do that. If you need this, you can always dip down and use Node Redis directly by calling `client.ft.search` with the appropriate query and arguments. That is, admittedly, a lot harder. But field-level queries aren't something that is planned for Redis OM.

Also, I would suggest that you not store passwords in the clear in a database—Redis or otherwise. Either encrypt them or store a cryptographic hash. If they are encrypted or hashed, then returning them won't be that big of a deal.

Not sure if you are actually doing that, of course. You could not want to return the encrypted password. Not an unreasonable requirement. But I would be remiss if I didn't point it out.

**Comment by errorcodezero** [comment]
My passwords are hashed but i would prefer users not be able to see hashes either. However thanks for the response.
