### ISSUE TITLE
RedisOM is fatally incompatible with proper JSON path schema for searching fields of objects in an array

### ISSUE THREAD

**Issue by jhmaster2000** [redis/redis-om-node#206]
**Using:**
* redis-om@0.4.2
* redis@4.6.7
* Redis v6.2.6
  * RediSearch v2.6.9
  * RedisJSON v2.4.7

Given the following sample JSON structure:
```json
{
    "settings": [
        { "type": 0 },
        { "type": 1 },
        { "type": 2 }
    ]
}
```
and the following matching schema, currently in the way RedisOM wants it:
```js
const SampleSchemaDefinition = {
    type: { type: 'number', path: '$.settings[*].type[*]' }
};
```
This works fine for RedisOM's core operations of saving and retrieving the entities, but falls apart as soon as search gets involved should you want to search the `type` fields. To ensure no possible extra interference from RedisOM internals we use raw search directly on a redis shell to test this:

Note: `Sample:index` is RedisOM's generated index for the above schema.
```sh
> FT.SEARCH Sample:index "@type:[-inf inf]"
```
This trivial search should naturally have returned every Sample entity, except for ones where the settings array is empty (`settings: []`) which while there are some empty ones in the real dataset, they are not the majority and there should have been results still, but instead the result is consistently nothing.

After some trial and error I find that changing the original schema to the following:
```js
const schemaDef = {
    type: { type: 'number', path: '$.settings[*].type' }
};
```
...will fix it on the search front, the same `FT.SEARCH` command above now yields the expected working results, all non-empty settings get retrieved. So surely that's it right? Problem solved? No, not quite...

While the fixed schema path worked for raw Redis search, RedisOM is unable to handle it when trying to perform any of the core save and retrieval operations, which invalidates the point of having `.search()` work if it dies on `.returnAll()` when trying to serialize the entities. The error? It is infact very explicit about this being the cause:
```
Error: Unexpected value for field 'type' of type 'number' from JSON path '$.settings[*].type' in Redis.
```

The result from all this ultimately renders searching completely unusable on this schema.

## Solutions
RedisOM should support the path without `[*]`, I don't know what the reasons for that restriction are, so I don't know how feasible that might be, so an alternative could also be to provide an additional field to override the path that is used on the RediSearch index compared to the one RedisOM will use.

**Comment by guyroyse** [comment]
The first JSONPath you provided—`$.settings[*].type[*]`—does not match anything in the JSON you provided. This is not a problem with Redis OM but is just how JSONPaths work. The problem is that this path will look for an array of objects—the `$.settings[*]` part—with a property of `type` that contains an _array_—the `.type[*]` part. The `type` property does not contain an array—it contains a single value. So, it doesn't match.

If your JSON looked like this, it _would_ work:

```json
{
  "settings": [
    { "type": [ 0, 1, 2 ] },
    { "type": [ 1 ] },
    { "type": [ 2, 4 ] }
  ]
}
```

However, this is not your JSON.

The second JSONPath that you provided—`$.settings[*].type`—is the correct one for your JSON. It matches the array of objects part using `$.settings[*]` and then looks for the `type` property within that array. It will return an array of the values in those `type` properties.

The error you are receiving is because the JSONPath returns an _array_ of numbers and not a _single_ number. But the type provided in the Schema is a `number`, which can only be a _single_ value. You need to change the type in the Schema to a `number[]` for this to work.

The section of the documentation on [overriding JSONPaths](https://github.com/redis/redis-om-node#configuring-json) talks about this:

> To do this, we'll need to specify the path property for the nested fields in the schema:
> 
> ```javascript
> const albumSchema = new Schema('album', {
>   artist: { type: 'string', path: '$.album.artist' },
>   title: { type: 'string', path: '$.album.title' },
>   year: { type: 'number', path: '$.album.year' },
>   genres: { type: 'string[]', path: '$.album.genres[*]' },
>   songDurations: { type: 'number[]', path: '$.album.songDurations[*]' },
>   outOfPublication: { type: 'boolean' }
> })
> ```
> There are two things to note here:
> 
> 1. We haven't specified a path for `outOfPublication` as it's still in the root of the document. It defaults to `$.outOfPublication`.
> 2. Our `genres` field points to a `string[]`. When using a `string[]` the JSONPath must return an array. **If it doesn't, an error will be generated.** (emphasis mine)
> 3. Same for our `songDurations`.

It's worth noting that the JSONPath needs to return multiple results (i.e. an array) but not a single result that _contains_ an array. This is why my examples use `[*]` at the end.

I might have been able to add code to make Redis OM smart enough to figure this specific case out and eliminate the need to add a `[*]` at the end when the leaf nodes of your tree are arrays. But even if RediSearch would have been happy with it—which I am not 100% sure it would be—this would have have added more complexity than is obvious. Plus, there were more important features to do first. _And_, I have future plans to add something like an `object` and `object[]` type that would obviate the need to specify JSONPaths in these scenarios.

**Comment by jhmaster2000** [comment]
I see, so it appears a misinterpretation of my part which for most common cases had no difference thus no impact ended up being exposed here where it finally made a difference, I was under the impression `type` was the type of the field *in the JSON*, as opposed to the reality that it seems to be the type of what the JSONPath returns, and in my defense after re-checking the README to be sure, it *is* worded in a way that gives off the idea its the type of the field data:

> The type property tells Redis OM what sort of **data is in that field**.

Perhaps the distinction that `type` is actually the JSONPath return type when working with JSON could be added on there for clarification? (at least until the `object` type is done, which I'll definitely be looking forward to)

Back to this specific issue itself the given fix indeed works, thank you 👍 Feel free to close the issue.
