### ISSUE TITLE
Implement missing `contain()` and `contains()` search functions

### ISSUE THREAD

**Issue by arsamsarabi** [redis/redis-om-node#26]
First issue. First of, awesome job 👍🏼 

Currently the `WhereString` class does not have an implementation of the abstract `contain` and `contains` functions declared in the `WhereField` class. Implementation of the missing "contain(s)" `WhereField` search functions in `WhereString` is required to return partial text matching.

I'm happy to create a PR for this if that's ok?

**Comment by guyroyse** [comment]
Thanks. Not missing, actually. The `WhereField` class does not define this. The interface, however, does. This interface is a superset of all the child methods on the class so that you can get pretty code completion and preserve typing in the fluent search API.

The `.contain` method itself is implemented in `WhereArray` and is used exclusively to determine if an array contains a specified string or not. So, for example, the array `[ 'foo', 'bar', 'baz' ]` might be checked with `.contains('bar')`. It's fairly limited and can only match the entire string.

For simple strings (i.e. those without full-text search enabled) RediSearch does not support substring searches. It either matches the entire string or it doesn't. For strings that have `textSearch: true` defined in the schema, you can use `. matchExact` to do a substring search.

Details are in the README:
- Searching Arrays: https://github.com/redis/redis-om-node#searching-arrays
- Full-text Search: https://github.com/redis/redis-om-node#full-text-search

**Comment by arsamsarabi** [comment]
Thank you for taking the time to explain this, and sorry about the rubbish issue 😄

**Comment by guyroyse** [comment]
No worries. I'm just happy people are using it and providing feedback. It's still a useful data point!
