### ISSUE TITLE
Add "expire" option when creating an Entity 

### ISSUE THREAD

**Issue by Witless** [redis/redis-om-node#35]
It would be great to add a TTL when you add a new Entity to a Repository, setting a default TTL on a repository could enhance this feature too!

**Comment by guyroyse** [comment]
Added to the backlog.

**Comment by dlschmidt** [comment]
Because I have a side project where I could use this feature, I've already started to implement this feature.
I think the implementation can certainly still be debated. 

https://github.com/dlschmidt/redis-om-node/tree/add-expire-option-when-creating-an-entity

Hopefully I'll get around to test the code in general and write tests in the next few days.

**Comment by Witless** [comment]
This is great, I also was about to use it in a project, thanks a lot!!! Hope it gets added with a similar implementation ^^

**Comment by guyroyse** [comment]
I've added this to the 0.2.0 which should be released tomorrow. It's a minimal solution but will address the need. I just added and `.expire()` method to the `Repository`. It will be easy enough to add TTL as an optional argument to `.save()` and `.createAndSave()` in future releases.

**Comment by guyroyse** [comment]
Release.
