### ISSUE TITLE
Repository class has no defined writeEntity method

### ISSUE THREAD

**Issue by littlecastrum** [redis/redis-om-node#58]
In the current version `0.2.0` the repository class is using inside it's save method the writeEntity method which has not being implemented making imposible to use it for its purpose

**Comment by guyroyse** [comment]
Redis OM 0.2.0 has breaking changes. One is that you can no longer call `new Repository()` as `Repository` is now an abstract base class. If you do—which JavaScript is happy to let you do—you will get this error because the `writeEntity` and `readEntity` methods are abstract methods and thus aren't implemented in the abstract base class.

To get a `Repository`, you need to instead call `client.fetchRepository(schema)` which will return either a `JsonRepository` or a `HashRepository` according to how your schema is configured. `JsonRepository` is the default.

Details on all the changes can be found in the [CHANGELOG](https://github.com/redis/redis-om-node/blob/main/CHANGELOG).

**Comment by littlecastrum** [comment]
This sorts everything, thanks for point out the changelog, didn't thought to check there
